#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."

echo " ==> ruff"
ruff check . --fix

echo " ==> pylint"
pylint custom_components

echo " ==> hassfest"
python3 -m script.hassfest --action validate